//
// Copyright (C) 2025 The Android Open-Source Project
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! This module implements the IMemoryBufferShare Android side service.

use crate::allocator::GapAllocator;
use android_trusty_membuf::aidl::android::trusty::membuf::{
    IMemoryBufferContext::BnMemoryBufferContext, IMemoryBufferContext::IMemoryBufferContext,
    IMemoryBufferShare::BnMemoryBufferShare, IMemoryBufferShare::IMemoryBufferShare,
    IMemoryBufferShare::HOST_BUFFER, IMemoryBufferShare::SECURE_DISPLAY_FRAME_BUFFER,
    IMemoryBufferShare::SECURE_VIDEO_DECODER_INPUT, IMemoryBufferShareVm::IMemoryBufferShareVm,
    MemoryBufferToken::MemoryBufferToken, ShareMemoryBufferResult::ShareMemoryBufferResult,
};
use binder::{self, AccessorProvider, ParcelFileDescriptor, Status, StatusCode, Strong};
use std::sync::{Mutex, OnceLock};

use thiserror::Error;

const SERVICE_NAME: &str = "android.trusty.membuf.IMemoryBufferShare/memshare_vm";
const VM_SERVICE_NAME: &str = "android.trusty.membuf.IMemoryBufferShareVm/memshare_vm";
const VM_ACCESSOR_NAME: &str = "android.os.IAccessor/IMemoryBufferShareVm/memshare_vm";

static ACCESSOR_PROVIDER: OnceLock<Option<AccessorProvider>> = OnceLock::new();
static MEMORY_SHARE_VM_SERVICE: OnceLock<Result<Strong<dyn IMemoryBufferShareVm>, MemShareError>> =
    OnceLock::new();
static MEMORY_MANAGER: OnceLock<Mutex<MemoryManager>> = OnceLock::new();

#[derive(Clone, Error, Debug)]
/// Errors generated by memshare library
pub enum MemShareError {
    #[error("Port configuration error for port: {0}")]
    /// Error when using binder function
    BinderError(String),
    #[error("Couldn't convert value")]
    /// Error when doing a cast
    ConversionError,
    #[error("Invalid value provided")]
    /// Value provided was not valid
    InvalidValue,
    #[error("Resources exhausted")]
    /// Couldn't do a memory allocation
    AllocationError,
    #[error("System was found on an invalid state")]
    /// System is currently on an invalid state
    InvalidState,
    #[error("Error found when mapping buffer")]
    /// Couldn't map a memory buffer
    BufferMappingProblem,
    #[error("An error occurred: {0}")]
    /// Generic issue found
    GenericError(String),
}

#[derive(Copy, Clone, Debug, PartialEq)]
enum ProtectionId {
    HostBuffer,
    SecureDisplayFrameBuffer,
    SecureVideoDecoderInput,
}

impl TryFrom<i32> for ProtectionId {
    type Error = MemShareError;

    fn try_from(value: i32) -> Result<Self, Self::Error> {
        match value {
            HOST_BUFFER => Ok(ProtectionId::HostBuffer),
            SECURE_DISPLAY_FRAME_BUFFER => Ok(ProtectionId::SecureDisplayFrameBuffer),
            SECURE_VIDEO_DECODER_INPUT => Ok(ProtectionId::SecureVideoDecoderInput),
            _ => {
                log::error!("Received invalid ProtectionId value: {value}");
                Err(MemShareError::ConversionError)
            }
        }
    }
}

#[derive(Clone, Debug)]
struct MemoryRange {
    protection_id: ProtectionId,
    range_ipa_start: u64,
    range_size: u64,
}

struct MemoryManager {
    host_allocator: GapAllocator,
    secure_allocator: GapAllocator,
}

impl MemoryManager {
    const HOST_RANGE_START: u64 = 0x8000_0000 + 64 * 1024 * 1024;
    const HOST_RANGE_END: u64 = Self::HOST_RANGE_START + 2 * 64 * 1024 * 1024;

    const SECURE_RANGE_START: u64 = 0x9000_0000;
    const SECURE_RANGE_END: u64 = Self::SECURE_RANGE_START + 6 * 64 * 1024 * 1024;

    const ALIGNMENT: u64 = 4096;

    fn new() -> Self {
        Self {
            host_allocator: GapAllocator::new(Self::HOST_RANGE_START..Self::HOST_RANGE_END),
            secure_allocator: GapAllocator::new(Self::SECURE_RANGE_START..Self::SECURE_RANGE_END),
        }
    }

    fn get_allocator(
        &mut self,
        protection_id: ProtectionId,
    ) -> Result<&mut GapAllocator, MemShareError> {
        match protection_id {
            ProtectionId::HostBuffer => Ok(&mut self.host_allocator),
            ProtectionId::SecureDisplayFrameBuffer => Ok(&mut self.secure_allocator),
            _ => {
                log::error!("Unsupported protection ID: {:?}", protection_id);
                Err(MemShareError::InvalidValue)
            }
        }
    }

    fn add_area(
        &mut self,
        protection_id: ProtectionId,
        base_address: u64,
        _size_bytes: u64,
    ) -> Result<(), MemShareError> {
        let allocator = self.get_allocator(protection_id)?;
        if allocator.dealloc(base_address) {
            Ok(())
        } else {
            log::error!(
                "Address {:#x} not found in allocator for {:?}",
                base_address,
                protection_id
            );
            Err(MemShareError::InvalidState)
        }
    }

    fn get_map_area(
        &mut self,
        size_bytes: i32,
        protection_id: ProtectionId,
    ) -> Result<(u64, u64), MemShareError> {
        if size_bytes <= 0 {
            log::error!("size_bytes was not positive: {size_bytes}");
            return Err(MemShareError::InvalidValue);
        }
        let size = size_bytes as u64;
        if !size.is_multiple_of(Self::ALIGNMENT) {
            log::error!("size must be multiple of {}, received {}", Self::ALIGNMENT, size);
            return Err(MemShareError::InvalidValue);
        }

        let allocator = self.get_allocator(protection_id)?;
        if let Some(start) = allocator.alloc(size, Self::ALIGNMENT) {
            Ok((start, start + size))
        } else {
            log::error!("No space left for protection ID {:?}", protection_id);
            Err(MemShareError::AllocationError)
        }
    }
}

struct MemoryBufferContextData {
    dma_buffer_id: Option<i32>,
    memory_range: Option<MemoryRange>,
    ta_memory_buffer_ctx: Option<Strong<dyn IMemoryBufferContext>>,
}

fn remove_memory_mapping(dma_buffer_id: i32) -> Result<(), MemShareError> {
    let vm = crate::MEMSHARE_VM.get().ok_or_else(|| {
        log::error!("MemShare VM object was not available");
        MemShareError::InvalidState
    })?;
    vm.remove_memory_mapping(dma_buffer_id)
}

impl MemoryBufferContextData {
    fn new(
        dma_buffer_id: i32,
        protection_id: ProtectionId,
        range_ipa_start: u64,
        range_size: u64,
    ) -> Self {
        let memory_range = MemoryRange { protection_id, range_ipa_start, range_size };
        MemoryBufferContextData {
            dma_buffer_id: Some(dma_buffer_id),
            memory_range: Some(memory_range),
            ta_memory_buffer_ctx: None,
        }
    }

    fn get_ipa(&self) -> Result<i64, MemShareError> {
        let memory_range = self.memory_range.as_ref().ok_or(MemShareError::InvalidState)?;
        // The values we are using for our memory map will not overflow an i64
        Ok(memory_range.range_ipa_start as i64)
    }

    fn free_resources(&mut self) -> Result<(), MemShareError> {
        if let Some(ta_memory_buffer_ctx) = self.ta_memory_buffer_ctx.take() {
            ta_memory_buffer_ctx.releaseMemoryBufferContext().map_err(|e| {
                log::error!("TA releaseMemoryBufferContext call failed: {:?}", e);
                MemShareError::GenericError("TA releaseMemoryBufferContext call failed".to_string())
            })?;
        }
        if let Some(dma_buffer_id) = self.dma_buffer_id.take() {
            remove_memory_mapping(dma_buffer_id)?;
        }
        if let Some(memory_range) = self.memory_range.take() {
            // MemoryBufferContext are only created after MEMORY_MANAGER is initialized
            let memory_manager = MEMORY_MANAGER.get().ok_or_else(|| {
                log::error!("Memory Manager was not available");
                MemShareError::InvalidState
            })?;
            memory_manager
                .lock()
                .map_err(|_| {
                    log::error!("found a poisoned memory_manager mutex on memory_manager");
                    MemShareError::InvalidState
                })?
                .add_area(
                    memory_range.protection_id,
                    memory_range.range_ipa_start,
                    memory_range.range_size,
                )
                .map_err(|e| {
                    log::error!(
                        "couldn't add area back: {:?} at address 0x{:x} of size {}",
                        e,
                        memory_range.range_ipa_start,
                        memory_range.range_size
                    );
                    MemShareError::GenericError(
                        "Coudln't return memory range to manager".to_string(),
                    )
                })?;
        }
        Ok(())
    }

    fn get_portable_token(&self) -> binder::Result<MemoryBufferToken> {
        let mem_buff_ctx = self.ta_memory_buffer_ctx.as_ref().ok_or_else(|| {
            log::error!("We do not have a TA IMemoryBufferContext to call");
            binder::Status::new_exception(
                binder::ExceptionCode::ILLEGAL_STATE,
                Some(c"Couldn't get TA IMemoryBufferContext"),
            )
        })?;
        mem_buff_ctx.getPortableToken()
    }
}

impl Drop for MemoryBufferContextData {
    fn drop(&mut self) {
        let e = self.free_resources();
        if e.is_err() {
            log::error!("MemoryBufferContextData drop encountered an error: {:?}", e);
        }
    }
}

struct MemoryBufferContext {
    memory_buffer_data: Mutex<MemoryBufferContextData>,
}

impl binder::Interface for MemoryBufferContext {}

impl MemoryBufferContext {
    fn new(
        dma_buffer_id: i32,
        protection_id: ProtectionId,
        range_ipa_start: u64,
        range_size: u64,
    ) -> Self {
        let memory_buffer_data =
            MemoryBufferContextData::new(dma_buffer_id, protection_id, range_ipa_start, range_size);
        MemoryBufferContext { memory_buffer_data: Mutex::new(memory_buffer_data) }
    }

    fn new_binder(
        self,
        ta_memory_buffer_ctx: Strong<dyn IMemoryBufferContext>,
    ) -> Strong<dyn IMemoryBufferContext> {
        self.memory_buffer_data.lock().expect("poisoned mutex").ta_memory_buffer_ctx =
            Some(ta_memory_buffer_ctx);
        BnMemoryBufferContext::new_binder(self, binder::BinderFeatures::default())
    }

    fn get_ipa(&self) -> Result<i64, MemShareError> {
        self.memory_buffer_data.lock().expect("poisoned mutex").get_ipa()
    }

    fn free_resources(&mut self) -> Result<(), MemShareError> {
        self.memory_buffer_data.lock().expect("poisoned mutex").free_resources()
    }
}

impl IMemoryBufferContext for MemoryBufferContext {
    fn getPortableToken(&self) -> binder::Result<MemoryBufferToken> {
        self.memory_buffer_data.lock().expect("poisoned mutex").get_portable_token()
    }

    fn releaseMemoryBufferContext(&self) -> Result<i32, Status> {
        self.memory_buffer_data.lock().expect("poisoned mutex").free_resources().map_err(|e| {
            log::error!("Couldn't free resources after TA released memory buffer context: {:?}", e);
            binder::Status::new_exception(
                binder::ExceptionCode::ILLEGAL_STATE,
                Some(c"Couldn't free resources after TA released memory buffer context"),
            )
        })?;
        Ok(0)
    }
}

fn get_mem_share_vm_service() -> Result<Strong<dyn IMemoryBufferShareVm>, MemShareError> {
    let _accessor_provider = ACCESSOR_PROVIDER
        .get_or_init(|| {
            AccessorProvider::new(&[VM_SERVICE_NAME.to_owned()], |s| {
                binder::wait_for_service(VM_ACCESSOR_NAME)
                    .and_then(|service| binder::Accessor::from_binder(s, service))
            })
        })
        .as_ref()
        .ok_or(MemShareError::BinderError("failed to create accessor provider".to_string()));
    MEMORY_SHARE_VM_SERVICE
        .get_or_init(|| {
            binder::wait_for_interface(VM_SERVICE_NAME).map_err(|_| {
                MemShareError::BinderError("Couldn't get IMemoryShareVM service".to_string())
            })
        })
        .clone()
}

struct MemoryBufferShare;

impl binder::Interface for MemoryBufferShare {}

impl IMemoryBufferShare for MemoryBufferShare {
    fn shareMemoryBuffer(
        &self,
        fd: &ParcelFileDescriptor,
        size_bytes: i32,
        protection_id: i32,
    ) -> binder::Result<ShareMemoryBufferResult> {
        let mem_share_vm_service = get_mem_share_vm_service().map_err(|e| {
            log::error!("Couldn't get mem share service: {:?}", e);
            binder::Status::new_exception(
                binder::ExceptionCode::ILLEGAL_STATE,
                Some(c"Couldn't get mem share service"),
            )
        })?;
        let mut mem_buf_ctx = map_memory_buffer(fd, size_bytes, protection_id).map_err(|e| {
            log::error!("Couldn't map memory buffer: {:?}", e);
            binder::Status::new_exception(
                binder::ExceptionCode::ILLEGAL_STATE,
                Some(c"Couldn't map memory buffer"),
            )
        })?;
        let ipa = mem_buf_ctx.get_ipa().map_err(|e| {
            log::error!("Get IPA failed: {:?}", e);
            binder::Status::new_exception(
                binder::ExceptionCode::ILLEGAL_STATE,
                Some(c"Couldn't get IPA for range"),
            )
        })?;
        let ta_memory_buffer_ctx = mem_share_vm_service
            .shareMemoryBuffer(ipa, size_bytes)
            .map_err(|e| {
                log::error!("shareMemoryBuffer in TA failed: {:?}", e);
                let free_res = mem_buf_ctx.free_resources();
                if free_res.is_err() {
                    log::error!("Free resources failed: {:?}", free_res);
                }
                e
            })?
            .context
            .ok_or_else(|| {
                log::error!("Received a null Memory Buffer CTX");
                binder::Status::new_exception(
                    binder::ExceptionCode::NULL_POINTER,
                    Some(c"TA returned a NULL ptr as Memory context"),
                )
            })?;
        Ok(ShareMemoryBufferResult { context: Some(mem_buf_ctx.new_binder(ta_memory_buffer_ctx)) })
    }
}

impl MemoryBufferShare {
    fn new_binder() -> Strong<dyn IMemoryBufferShare> {
        BnMemoryBufferShare::new_binder(MemoryBufferShare, binder::BinderFeatures::default())
    }
}

/// Registers the IMemoryBufferShare service with the service manager
pub fn register_memshare_service() -> Result<(), StatusCode> {
    binder::add_service(SERVICE_NAME, MemoryBufferShare::new_binder().as_binder())
}

fn add_memory_mapping(
    fd: &ParcelFileDescriptor,
    range_ipa_start: u64,
    range_ipa_end: u64,
) -> Result<i32, MemShareError> {
    let vm = crate::MEMSHARE_VM.get().ok_or_else(|| {
        log::error!("MemShare VM object was not available");
        MemShareError::InvalidState
    })?;
    vm.add_memory_mapping(fd, range_ipa_start, range_ipa_end)
}

fn map_memory_buffer(
    fd: &ParcelFileDescriptor,
    size_bytes: i32,
    protection_id: i32,
) -> Result<MemoryBufferContext, MemShareError> {
    // TODO: Hardcoded values will need to match what is provided to TA
    if size_bytes < 0 {
        log::error!("size_bytes was negative: {size_bytes}");
        return Err(MemShareError::InvalidValue);
    }
    let protection_id: ProtectionId = protection_id.try_into()?;
    let memory_manager = MEMORY_MANAGER.get_or_init(|| Mutex::new(MemoryManager::new()));
    let (range_ipa_start, range_ipa_end) =
        memory_manager.lock().expect("poisoned mutex").get_map_area(size_bytes, protection_id)?;
    log::info!("Mapping fd {fd:?} at start: {range_ipa_start:#x} end: {range_ipa_end:#x}");
    let dma_buffer_id = add_memory_mapping(fd, range_ipa_start, range_ipa_end)?;
    if dma_buffer_id < 0 {
        log::error!("Couldn't add dma buffer. Received: {}", dma_buffer_id);
        memory_manager.lock().expect("poisoned mutex").add_area(
            protection_id,
            range_ipa_start,
            range_ipa_end - range_ipa_start,
        )?;
        return Err(MemShareError::BufferMappingProblem);
    }
    let mem_buf_ctx =
        MemoryBufferContext::new(dma_buffer_id, protection_id, range_ipa_start, size_bytes as u64);
    Ok(mem_buf_ctx)
}
